# Top-level Cloud Build config that builds the backend image from ./backend
# This file exists so Cloud Build triggers that look for 'cloudbuild.yaml' at repo root will succeed.
# Usage example (via gcloud):
# gcloud builds submit --config=cloudbuild.yaml --substitutions=_IMAGE=gcr.io/$PROJECT_ID/mood-playlist-backend,_SERVICE=mood-playlist-backend,_REGION=us-central1

steps:
  - id: 'Build backend image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE}', './backend']

  - id: 'Push image to Container Registry'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}']

  - id: 'Optional deploy to Cloud Run'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "${_DEPLOY}" = "true" ]; then
          echo "Deploying ${_IMAGE} to Cloud Run service ${_SERVICE} in ${_REGION}...";
          gcloud run deploy ${_SERVICE} --image ${_IMAGE} --region ${_REGION} --platform managed --allow-unauthenticated;
        else
          echo "_DEPLOY not set to true; skipping Cloud Run deployment.";
        fi

images:
  - '${_IMAGE}'

substitutions:
  _IMAGE: gcr.io/$PROJECT_ID/mood-playlist-backend:latest
  _SERVICE: mood-playlist-backend
  _REGION: us-central1
  _DEPLOY: 'false'

options:
  logging: CLOUD_LOGGING_ONLY
