steps:
  # Build the backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mood-playlist-backend', './backend']

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mood-playlist-backend']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', 'mood-playlist-backend',
        '--image', 'gcr.io/$PROJECT_ID/mood-playlist-backend',
        '--platform', 'managed',
        '--region', 'us-central1',
        '--allow-unauthenticated',
        '--port', '5000'
      ]

options:
  logging: CLOUD_LOGGING_ONLY
