# Cloud Build config to build backend image and optionally deploy to Cloud Run.
# Usage examples:
# gcloud builds submit --config=backend/cloudbuild.yaml --substitutions=_IMAGE=mood-playlist-backend,_SERVICE=mood-playlist-backend,_REGION=us-central1
# or to deploy: add ,_DEPLOY=true

steps:
  - id: 'Build Docker image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE}', '.']

  - id: 'Push image to Container Registry'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}']

# Optional: Deploy to Cloud Run when _DEPLOY=true
  - id: 'Deploy to Cloud Run'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "${_DEPLOY}" = "true" ]; then
          echo "Deploying ${_IMAGE} to Cloud Run service ${_SERVICE} in ${_REGION}...";
          gcloud run deploy ${_SERVICE} --image ${_IMAGE} --region ${_REGION} --platform managed --allow-unauthenticated;
        else
          echo "_DEPLOY not set to true; skipping Cloud Run deployment.";
        fi

images:
  - '${_IMAGE}'

substitutions:
  _IMAGE: gcr.io/$PROJECT_ID/mood-playlist-backend:latest
  _SERVICE: mood-playlist-backend
  _REGION: us-central1
  _DEPLOY: 'false'

options:
  logging: CLOUD_LOGGING_ONLY
